default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: movie_reviewer_2024_v1_development
  password: <%= ENV['LOCAL_PASSWORD'] %>
  username: <%= ENV['LOCAL_USERNAME'] %>

test:
  <<: *default
  database: movie_reviewer_2024_v1_test

production:
  <<: *default
  database: movie_reviewer_2024_v1_production
  username: movie_reviewer_2024_v1
  password: <%= ENV["MOVIE_REVIEWER_2024_V1_DATABASE_PASSWORD"] %>
